name: jupyter-env

channels:
  - defaults
  - conda-forge

dependencies:
  - ipython
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - plotly
  - geopandas
  - contextily
  - pip
  - python
  - scikit-learn
